name: scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SCRIPT_CACHE_LOCATION: ${{ github.workspace }}/.cache
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: checkout scripts
      uses: actions/checkout@v2
      with:
        path: scripts
    - name: checkout shared
      uses: actions/checkout@v2
      with:
        repository: DanielEgbers/Actions.Shared
        path: Actions.Shared
    - name: checkout data
      env:
        DATA_REPO: ${{ secrets.DATA_REPO }}
      run: |-
        git clone $DATA_REPO data
    - name: restore tools
      id: restore-tools
      uses: actions/cache@v2
      with:
        path: .tools
        key: tools-${{ runner.os }}-${{ hashFiles('.tools/dotnet-script') }}
    - name: install tools
      if: steps.restore-tools.outputs.cache-hit != 'true'
      run: |-
        dotnet tool install --tool-path .tools dotnet-script
    - name: restore packages
      uses: actions/cache@v2
      with:
        path: ${{ env.NUGET_PACKAGES }}
        key: packages-${{ runner.os }}-${{ github.sha }}
    - name: prepare
      run: |-
        .tools/dotnet-script --debug scripts/actions.csx -- --help
    - name: scrape WasLosIn
      run: |-
        .tools/dotnet-script scripts/actions.csx scrape WasLosIn
    # - name: scrape Geeste
    #   run: |-
    #     .tools/dotnet-script scripts/actions.csx scrape Geeste
    - name: push
      run: |-
        .tools/dotnet-script scripts/actions.csx push
    - name: debug
      run: |-
        ls -la